name: Release CI
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  linuxbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Set Version
        run: VERSION=${{ github.event.release.tag_name }} && mvn -B versions:set -DnewVersion=${VERSION:1} -DgenerateBackupPoms=false
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build
        shell: bash
        run: mvn clean install -DrepoBaseUrl=https://github.com/EXXETA/correomqtt-plugins/releases/download/${{ github.event.release.tag_name }}/
      - name: Release 
        uses: xresloader/upload-to-github-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          file: '**/target/*.jar,default-repo.json'
          tags: true
